"""1.2 upgrade

Revision ID: bf48c236ba15
Revises:
Create Date: 2021-05-03 09:01:25.774771

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bf48c236ba15"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("IP", sa.String(length=46), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("failed", sa.Boolean(), nullable=True),
        sa.Column("flushed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "group", "fullname", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    op.alter_column(
        "group", "shortname", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column(
        "group", "uuid", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.alter_column(
        "role", "description", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("role", "name", existing_type=sa.VARCHAR(length=80), nullable=False)
    op.alter_column(
        "token",
        "creation",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column("token", "jti", existing_type=sa.VARCHAR(length=36), nullable=False)
    op.alter_column("token", "token", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "token", "token_type", existing_type=sa.VARCHAR(length=1), nullable=False
    )
    op.drop_column("token", "hostname")
    op.alter_column(
        "user", "authmethod", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "user", "surname", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("user", "uuid", existing_type=sa.VARCHAR(length=36), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "uuid", existing_type=sa.VARCHAR(length=36), nullable=True)
    op.alter_column(
        "user", "surname", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "user", "authmethod", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.add_column(
        "token",
        sa.Column(
            "hostname", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "token", "token_type", existing_type=sa.VARCHAR(length=1), nullable=True
    )
    op.alter_column("token", "token", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("token", "jti", existing_type=sa.VARCHAR(length=36), nullable=True)
    op.alter_column(
        "token",
        "creation",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column("role", "name", existing_type=sa.VARCHAR(length=80), nullable=True)
    op.alter_column(
        "role", "description", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("group", "uuid", existing_type=sa.VARCHAR(length=36), nullable=True)
    op.alter_column(
        "group", "shortname", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "group", "fullname", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    op.drop_table("login")
    # ### end Alembic commands ###
