---
project:
  title: BlueCloud
  description: "REST APIs for BlueCloud Data Cache"
  version: "0.7"
  rapydo: "2.4"

variables:
  env:
    MARIS_EXTERNAL_API_SERVER: "**PLACEHOLDER**"

    FRONTEND_FRAMEWORK: nofrontend
    CORS_ALLOWED_ORIGIN: "*"
    AUTH_SERVICE: sqlalchemy
    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1
    ACTIVATE_REDIS: 1
    ACTIVATE_CELERY: 1
    # ACTIVATE_FLOWER: 1
    CELERY_ENABLE_CONNECTOR: 1
    MAX_ZIP_SIZE: 2147483648
    LOCK_SLEEP_TIME: 30
